### PR TITLE
Turn the Scijava kernel into a polyglot kernel

### PR DESCRIPTION
**Pull request by hadim**

### CODE REVIEW

**Comment by hadim** [comment]
So the implementation is working. Bindings between engines are also synced which allow re-using variables between different languages in the same notebook.

The only think I am not happy with is the syntax color that is wrong because all the cells are now independent and I don't know how to set a language for an individual cell (is that even possible ?).

**Comment by hadim** [comment]
ping @ctrueden (if you have time)

**Comment by hadim** [comment]
For syntax highlighting, see this https://github.com/jupyterlab/jupyterlab/issues/2143

**Comment by hadim** [comment]
And here is a notebook example  : https://gist.github.com/hadim/f0916cfdd242c074c11f3f81a9487d76

**Comment by ctrueden** [comment]
@hadim This is awesome. It looks like it actually simplified matters, too.

For the syntax highlighting, perhaps we could create a new "meta-highlighter" that does the right thing based on the shebang at the beginning. I guess it depends on how the highlighter library works—how powerful it is.

**Comment by ctrueden** [comment]
Any reason not to merge it? (After fixing conflicts of course.)

**Comment by hadim** [comment]
Yeah, only the lack of syntax makes me not merge it. On the client side, it does not look that feature gonna come soon (see https://github.com/jupyterlab/jupyterlab/issues/2143).

If you want it I am ok to merge it. I guess we can live with Groovy syntax only for now.

**Pull request merged**
