### PR TITLE
Display all outputs in notebook-friendly form

### PR DESCRIPTION
**Pull request by hadim**
More appropriate for discussion. @ctrueden

### CODE REVIEW

**Comment by hadim** [comment]
I feel the infinite recursion tricking us :-)

**Comment by hadim** [comment]
Hum I only got two print from `HTMLNotebookOutputConverter.asHTML()`... so it might not be infinite recursion.

**Comment by hadim** [comment]
Got it. One of the ouput was `null` and so stuck when calling `asHTML` on it without throwing a `NullException` ?

**Comment by hadim** [comment]
Something is wrong on the SJC side because both `output.getValue(module);` and `module.getOutput(ScriptModule.RETURN_VALUE);` always return `null`.

**Comment by hadim** [comment]
I can't figure out what's wrong exactly but it seems to be something related to the conversion.

For example, when the return value is an integer, conversion returns a `null` which is not the intended behavior.

I'm done for today...

**Comment by ctrueden** [comment]
Thanks for digging! Seems more tractable to fix now.

**Comment by awalter17** [comment]
@hadim and @ctrueden 

I am finished with my changes! Everything appears to be working as expected in my notebooks. Additionally, I rebased this branch over master and cleaned up the commits a bit. So this should be good to merge. Please let me know if you have any questions/concerns.

Cheers, 

Alison

**Comment by ctrueden** [comment]
@awalter17 Thank you very much; I did extensive testing with the ImageJ tutorial notebooks on the `convert-nb-to-jupyter` branch, and it is working extremely well now. So I merged it!

**Comment by ctrueden** [comment]
@awalter17 @hadim I also updated the `convert-nb-to-jupyter` branch of imagej/tutorials to take advantage of this latest progress, and pushed the result. (Actually, force-pushed—@awalter17 I rewrote your WIP to say "Progress on..." instead. We may not need to rewrite that branch's history again, since it is already reasonable enough.)

Just [look how awesome the Ops notebook is now](https://nbviewer.jupyter.org/github/imagej/tutorials/blob/convert-nb-to-jupyter/notebooks/1.%20Using%20ImageJ/2.%20Introduction%20to%20ImageJ%20Ops.ipynb)!

**Pull request merged**
